# Generated by Django 2.2.5 on 2019-10-25 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glasses_model', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Glasses',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('glasses_availables', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('init_hour', models.DateTimeField()),
                ('final_hour', models.DateTimeField()),
                ('num_persons', models.IntegerField()),
                ('glasses', models.ManyToManyField(to='vr.Glasses')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vr.Room')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
        migrations.AddField(
            model_name='glasses',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vr.Room'),
        ),
    ]
